useLegacyDatetimeCode=false&serverTimezone=UTC

spring.application.name=DataSourcesEx3

spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.datasource.username=your_pg_username
spring.datasource.password=your_pg_password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
