### Get all purchases
GET http://localhost:8080/purchase

### Create a purchase
POST http://localhost:8080/purchase
Content-Type: application/json

{
  "product": "Spring Security in Action #2",
  "price": 26.2
}
