### Get all purchases
GET http://localhost:8080/accounts

### Create a purchase
POST http://localhost:8080/transfer
Content-Type: application/json

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 1.50
}

### Create a purchase
POST http://localhost:8080/transfer
Content-Type: application/json

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 1.50
}
