### Get all purchases
GET http://localhost:8080/purchase

### Create a purchase
POST http://localhost:8080/purchase
Content-Type: application/json

{
  "id": 1,
  "product": "Spring Security in Action",
  "price": 25.2
}
